#ifndef IRQ_HANDLERS_H
#define IRQ_HANDLERS_H

void NMI_Handler(void);
void HardFault_Handler(void);
void MemoryManagement_Handler(void);
void BusFault_Handler(void);
void UsageFault_Handler(void);
void SVC_Handler(void);
void DebugMonitor_Handler(void);
void PendSV_Handler(void);
void SysTick_Handler(void);
void GPIOA_IRQHandler(void);
void GPIOB_IRQHandler(void);
void GPIOC_IRQHandler(void);
void GPIOD_IRQHandler(void);
void GPIOE_IRQHandler(void);
void UART0_IRQHandler(void);
void UART1_IRQHandler(void);
void SSI0_IRQHandler(void);
void I2C0_IRQHandler(void);
void PWMFault_IRQHandler(void);
void PWMGen0_IRQHandler(void);
void PWMGen1_IRQHandler(void);
void PWMGen2_IRQHandler(void);
void QEI0_IRQHandler(void);
void ADC0Seq0_IRQHandler(void);
void ADC0Seq1_IRQHandler(void);
void ADC0Seq2_IRQHandler(void);
void ADC0Seq3_IRQHandler(void);
void WDTimer0_IRQHandler(void);
void Timer0A_IRQHandler(void);
void Timer0B_IRQHandler(void);
void Timer1A_IRQHandler(void);
void Timer1B_IRQHandler(void);
void Timer2A_IRQHandler(void);
void Timer2B_IRQHandler(void);
void AnalogCmp0_IRQHandler(void);
void AnalogCmp1_IRQHandler(void);
void SC_IRQHandler(void);
void FMC_IRQHandler(void);
void GPIOF_IRQHandler(void);
void GPIOG_IRQHandler(void);
void UART2_IRQHandler(void);
void Timer3A_IRQHandler(void);
void Timer3B_IRQHandler(void);
void I2C1_IRQHandler(void);
void QEI1_IRQHandler(void);
void Ethernet_IRQHandler(void);
void Hibernation_IRQHandler(void);

#endif
